// <auto-generated />
using EFCoreBug.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EFCoreBug.Migrations
{
    [DbContext(typeof(NoteDbContext))]
    [Migration("20171026105930_userAdd")]
    partial class userAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreBug.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("EFCoreBug.Note", b =>
                {
                    b.OwnsOne("EFCoreBug.User", "User", b1 =>
                        {
                            b1.Property<Guid>("NoteId");

                            b1.Property<string>("Email");

                            b1.Property<string>("Fullname");

                            b1.ToTable("Note");

                            b1.HasOne("EFCoreBug.Note")
                                .WithOne("User")
                                .HasForeignKey("EFCoreBug.User", "NoteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
